# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Downloader import Downloader
from pytube import exceptions

class Ui_MainWindow(object):
    downloader = None

    def setVideoData(self):
        link = self.link.text()

        try:
            self.downloader = Downloader(link, self)
        except:
            self.searchResult.setText('Link mal formatado!')
            self.searchResult.setStyleSheet("color: rgb(255, 0, 0);")
            return

        info = self.downloader.getVideoInfo()

        try:
            title = info.title
            author = info.author
        except exceptions.VideoUnavailable:
            self.searchResult.setText('Video indisponível!')
            self.searchResult.setStyleSheet("color: rgb(255, 0, 0);")
            return

        self.videoTitle.setText('Nome: ' + title)
        self.videoChannel.setText('Canal: ' + author)
        self.searchResult.setText('Video encontrado!')
        self.searchResult.setStyleSheet("color: rgb(0, 255, 0);")

        self.downloadVideo.setEnabled(True)
        self.downloadSong.setEnabled(True)

    def downloadAsSong(self):
        self.downloader.download('music')

    def downloadAsVideo(self):
        self.downloader.download('video')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(210, 60, 391, 131))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("assets/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.link = QtWidgets.QLineEdit(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(12, 240, 701, 31))
        self.link.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.link.setObjectName("link")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(720, 240, 61, 31))
        self.search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search.setObjectName("search")
        self.videoData = QtWidgets.QFrame(self.centralwidget)
        self.videoData.setGeometry(QtCore.QRect(10, 290, 771, 231))
        self.videoData.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.videoData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoData.setObjectName("videoData")
        self.searchResult = QtWidgets.QLabel(self.videoData)
        self.searchResult.setGeometry(QtCore.QRect(10, 12, 751, 21))
        self.searchResult.setStyleSheet("color: rgb(255, 0, 0);")
        self.searchResult.setObjectName("searchResult")
        self.videoTitle = QtWidgets.QLabel(self.videoData)
        self.videoTitle.setGeometry(QtCore.QRect(10, 70, 761, 16))
        self.videoTitle.setObjectName("videoTitle")
        self.videoChannel = QtWidgets.QLabel(self.videoData)
        self.videoChannel.setGeometry(QtCore.QRect(10, 90, 761, 16))
        self.videoChannel.setObjectName("videoChannel")
        self.downloadSong = QtWidgets.QPushButton(self.videoData)
        self.downloadSong.setEnabled(False)
        self.downloadSong.setGeometry(QtCore.QRect(260, 190, 101, 23))
        self.downloadSong.setObjectName("downloadSong")
        self.downloadVideo = QtWidgets.QPushButton(self.videoData)
        self.downloadVideo.setEnabled(False)
        self.downloadVideo.setGeometry(QtCore.QRect(370, 190, 101, 23))
        self.downloadVideo.setObjectName("downloadVideo")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 542, 771, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.search.clicked.connect(self.setVideoData)
        self.downloadSong.clicked.connect(self.downloadAsSong)
        self.downloadVideo.clicked.connect(self.downloadAsVideo)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Downloader"))
        self.search.setText(_translate("MainWindow", "OK"))
        self.searchResult.setText(_translate("MainWindow", "Video não encontrado!"))
        self.videoTitle.setText(_translate("MainWindow", "Nome:"))
        self.videoChannel.setText(_translate("MainWindow", "Canal:"))
        self.downloadSong.setText(_translate("MainWindow", "Baixar música"))
        self.downloadVideo.setText(_translate("MainWindow", "Baixar video"))
